services:
  frontend: 
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - 3000:3000
    container_name: doorbellcam_frontend
    environment:
      - REACT_APP_BASE_URL=http://localhost:8080
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: flask --app __init__.py run --reload --debugger --host=0.0.0.0
    volumes:
      - ./backend:/srv/app
      - ./captures:/srv/app/captures
    stdin_open: true
    tty: true
    ports:
      - 8080:5000
    container_name: doorbellcam_backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      - POSTGRES_USER=iot_user
      - POSTGRES_PASSWORD=testpw
      - POSTGRES_DB=development
      - POSTGRES_HOST=db

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    container_name: doorbellcam_db
    environment:
      POSTGRES_USER: iot_user
      POSTGRES_PASSWORD: testpw
      POSTGRES_DB: development
      PGDATA: /var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U iot_user -d development"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db_data_655:/var/lib/postgresql/data/pgdata

  adminer:
    image: adminer
    restart: always
    ports:
      - 5001:8080
    container_name: doorbellcam_dbadminer
  
volumes:
  db_data_655: